### ISSUE TITLE
What is the purpose of Utils.getLatLong() ?

### ISSUE THREAD

**Issue by AblionGE** [AblionGE/LocPrivLib#7]
Hello,

I'm not sure to understand what does this function : https://github.com/AblionGE/LocPrivLib/blob/maschaer_semester_project/app/src/main/java/org/epfl/locationprivacy/util/Utils.java#L60-L74

It seems that it computes the bottom left point of a cell to draw it, but I don't understand everything in this function. Why should we divide the distance by 6371.0 ?

Thanks

**Comment by AblionGE** [comment]
This function is only used to generate the grid (that can be drawn) and I need to set the `distance` argument with the current `height` and `width` values of the cell.

**Comment by berkeragir** [comment]
Hi Marc, this function actually uses the 'Havesine formula'. The number 6371.0 is the average radius of Earth in kilometers. Basically, given a point on Earth (i.e., one pair of coordinates), the distance on the planet's surface you want to cover and the bearing (i.e., the angle with respect to North), it computes the destination coordinates (the formula itself is actually for any sphere; that's why you have the radius in calculation). The code is unfortunately not well-commented by the previous author; this should have been mentioned in the function description.

Here is more information:
https://en.wikipedia.org/wiki/Haversine_formula

**Comment by AblionGE** [comment]
Okay Thanks :+1:
